# Generated by Django 4.1.7 on 2023-04-22 13:48

from django.db import migrations, models
import utils.upload_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('image', models.ImageField(upload_to=utils.upload_image.upload_instance_image, verbose_name='Изображение')),
                ('genres', models.ManyToManyField(related_name='genres', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
